---
- name: creates shard settings
  template:
    src: server/server.ini.j2
    dest: '{{ dst_persistent_storage_root }}/{{ dst_conf_dir }}/{{ dst_cluster_name }}/{{ dst_shard_name }}/server.ini'
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user }}'
    mode: '0644'

- name: creates world generation file.
  template:
    src: server/worldgenoverride.lua.j2
    dest: '{{ dst_persistent_storage_root }}/{{ dst_conf_dir }}/{{ dst_cluster_name }}/{{ dst_shard_name }}/worldgenoverride.lua'
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user }}'
    mode: '0644'
