---
- name: ensures that server directory `{{ dst_persistent_storage_root }}/{{ dst_conf_dir }}/{{ dst_cluster_name }}/{{ dst_shard_name }}/` exists
  file:
    path: '{{ dst_persistent_storage_root }}/{{ dst_conf_dir }}/{{ dst_cluster_name }}/{{ dst_shard_name }}'
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user }}'
    mode: '0755'
    recurse: yes
    state: directory

- name: creates cluster token file
  template:
    src: cluster/cluster_token.txt.j2
    dest: '{{ dst_persistent_storage_root }}/{{ dst_conf_dir }}/{{ dst_cluster_name }}/cluster_token.txt'
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user }}'
    mode: '0644'

- name: creates cluster settings
  template:
    src: cluster/cluster.ini.j2
    dest: '{{ dst_persistent_storage_root }}/{{ dst_conf_dir }}/{{ dst_cluster_name }}/cluster.ini'
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user }}'
    mode: '0644'
