---

- name: copy server init script into place
  template:
    src: systemd/dst.service.j2
    dest: /etc/systemd/system/dst-{{ dst_shard_name }}.service
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user }}'
    mode: '0644'

- name: create dst-service-settings.cfg
  copy:
    content: OPTS="-persistent_storage_root {{ dst_persistent_storage_root }} -conf_dir {{ dst_conf_dir }} -cluster {{ dst_cluster_name }} -shard {{ dst_shard_name }}"
    dest: '{{ dst_install_dir }}/bin/dst-service-settings.cfg'
    owner: '{{ steamcmd_user }}'
    group: '{{ steamcmd_user }}'
    mode: '0644'

- name: ensure the server is enabled and will start on boot
  service:
    name: dst-{{ dst_shard_name }}
    state: started
    enabled: yes
